### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/compassist#13]
Group 19

Congrats on finishing Milestone 1! We can see that you put some thought into this project. Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

- [x] There isn't an issue by function in the package - mechanics -2

- [x] "Collab: Finalize Functions + Prelim Function Scope" There are milestone issues that are still open -2 

Great job group 19! I love this idea, I think it’s very unique project. Remember to create issues based on functions, and assign them to team members! As a side note remember to have every member commit in the GitHub repo equally. This group had big difference in commits. I am a bit confused on some of the functions. How would an individual know the drop rate of an item, unless that individual did some sort of web search is that the case? Also the contributors on the side Ashwin Babu seems to not have contributed even though he had commits. Is this a GitHub error?

**Comment by samson-bakos** [comment]
Thanks for the feedback @andytai7 !  Regarding the commits, we understand there was a commit difference, but I think that was more to do with the week's expectations; it was mostly just collaborating and setup, which is basically a one person job, though we did divide up small things like contributing files, readme, etc. We now each have our own function/ test suite to write, so it should even out. Ashwin wrote the CONDUCT.md file, not sure why his contribution appeared differently

**Comment by samson-bakos** [comment]
Regarding the rates, yes the expectation is the user knows the rates which are publicly available on the internet, but wants to know the total time, or how unlucky they are. The original inspiration for my function (boss_completion) that then spawned the discussion that turned into our other functions was from a problem I ran into playing Runescape. I knew the drop rate of the items I wanted https://oldschool.runescape.wiki/w/Chest_(Tombs_of_Amascut)#Opened  (Uniques), and knew that at the difficulty I played at I had a ~1/33 chance of receiving a drop per raid. I wanted to know the expected time to completion, but this ended up taking me a while as each of the 5040 different combination orders have a different expected kildcount, and probability of occurring, and the correct result is the weighted average of all of them (791 killcount or 527 hours in my case, oh boy). This is a very common problem in drop based video games, but its usually simpler because items have the same drop rate (https://oldschool.runescape.wiki/w/Zulrah -- 4 items all same rate). Because this problem is generalizable we didn't want to do any API scraping -- we want these to be able to be used for any drop rate or luck based game so we left it open ended. You won't find a completionist who doesn't know the rate for the item they're hunting though
