### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/compassist#41]
> **Congratulations on finishing milestone 2!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}

Great job!

#### 1. Create project structure for the R project
rubric={mechanics:20}

Well done!
 
 Comments:
It is recommended to include sections in `README.md` rather than one section for everything.

## 3. R package function specifications
rubric={quality:10}

- [ ] The documentation (3 out of 4 functions) has no examples. - **quality -2**

## 4. Specific expectations for this milestone are:
rubric={mechanics:10}

Well done!

## 5. Submission instructions
rubric={mechanics:10}

Well done!

**Comment by samson-bakos** [comment]
Hi @negsadr, 
Regarding the conduct file, I can see it on the 0.1.0 version of this repo, it is called CONDUCT.md.

Also, regarding examples in the documentation; we're a little confused by the expectation there. In the previous week for the Python package, we were not expected to provide function examples before writing the function itself because we weren't sure about the outputs/ if changes would be made. Since the expectation for this week was basic docstrings only it didn't make sense to provide an example for each since that's something that comes from a fully realized function -- our Milestone 3 version has examples now.

**Comment by negsadr** [comment]
Hi @samson-bakos 

Thanks for your message. I've modified your grade for the code of conduct.

Thanks for adding examples in your milestone 3. Please note that you are expected to [follow the standards](https://py-pkgs.org/06-documentation) for documentations in every step, including milestone 1.

Feel free to reach out if you have any other questions.
